on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    uses: gardenlinux/package-build/.github/workflows/build.yml@main
    with:
      release: ${{ github.ref == 'refs/heads/main' }}
      build_dep: |
        gardenlinux/package-golang 1.24.4-1gl0+bp1592
        gardenlinux/bp-package-golang-golang-x-net-dev 0.27.0-2gl2+bp1592
        gardenlinux/bp-package-golang-net 0.33.0-1gl1+bp1592
        gardenlinux/bp-package-golang-x-crypto 0.36.0-1+exp1gl2+bp1592
